<?php 
$set_data_a = array(
	array(
		'form_name'=>'roomcategory',
		'title'=>'Room Category',
		'mandatory'=>'Y',
		'input_type'=>'text',
		'input_value'=>'1 BED',
		'column'=>'col-12 col-xl-6',
		'readonly'=>'',
		'disabled'=>'Y',
	),
	array(
		'form_name'=>'roomDimension',
		'title'=>'Room size (sq.m.)',
		'mandatory'=>'Y',
		'input_type'=>'number',
		'input_value'=>'24',
		'column'=>'col-12 col-md-4 col-xl-2',
		'readonly'=>'',
		'disabled'=>'',
	),
	array(
		'form_name'=>'maximumPaxRoom',
		'title'=>'Maximum Pax/Room',
		'mandatory'=>'Y',
		'input_type'=>'number',
		'input_value'=>'2',
		'column'=>'col-6 col-md-4 col-xl-2',
		'readonly'=>'',
		'disabled'=>'',
	),
	array(
		'form_name'=>'totalRooms',
		'title'=>'Total rooms',
		'mandatory'=>'Y',
		'input_type'=>'number',
		'input_value'=>'12',
		'column'=>'col-6 col-md-4 col-xl-2',
		'readonly'=>'',
		'disabled'=>'',
	),
	/*
	array(
		'form_name'=>'hotelChain',
		'title'=>'Hotel chain',
		'mandatory'=>'Y',
		'input_type'=>'select',
		'selection'=>array(
			array('data'=>'No chain'),
			array('data'=>'Accor'),
			array('data'=>'Amari'),
			array('data'=>'Best Western'),
			array('data'=>'Blue Tree'),
			array('data'=>'Hilton'),
		),
		'column'=>'col-12 col-lg-6',
		'readonly'=>'',
		'disabled'=>'',
	),
	array(
		'form_name'=>'hotelStyle',
		'title'=>'Hotel style',
		'mandatory'=>'Y',
		'input_type'=>'select',
		'selection'=>array(
			array('data'=>'Select style'),
			array('data'=>'Airport Hotel'),
			array('data'=>'Beach Resort'),
			array('data'=>'Boutique'),
			array('data'=>'Classic'),
			array('data'=>'Golf course'),
			array('data'=>'Home stay'),
			array('data'=>'Hotel and Residence'),
			array('data'=>'Hostel'),
			array('data'=>'Resort'),
			array('data'=>'Riverside'),
			array('data'=>'Villa'),
		),
		'column'=>'col-12 col-md-6 col-lg-3',
		'readonly'=>'',
		'disabled'=>'',
	),
	array(
		'form_name'=>'Currency',
		'title'=>'Currency',
		'mandatory'=>'Y',
		'input_type'=>'select',
		'selection'=>array(
			array('data'=>'Select currency'),
			array('data'=>'USD - US Dollar'),
			array('data'=>'JPY - Japanese Yen'),
			array('data'=>'WON - Korean Won'),
			array('data'=>'THB - Thai Baht'),
		),
		'column'=>'col-12 col-md-6 col-lg-3',
		'readonly'=>'',
		'disabled'=>'',
	),
	array(
		'form_name'=>'hotelCode',
		'title'=>'Hotel code',
		'mandatory'=>'Y',
		'input_type'=>'text',
		'input_value'=>'NNT000057',
		'column'=>'col-12 col-md-6 col-lg-3',
		'readonly'=>'',
		'disabled'=>'Y',
	),
	array(
		'form_name'=>'xmlCode',
		'title'=>'Web Service XML code',
		'mandatory'=>'Y',
		'input_type'=>'text',
		'input_value'=>'WSASTHNNT000057',
		'column'=>'col-12 col-md-6 col-lg-3',
		'readonly'=>'',
		'disabled'=>'Y',
	),
	array(
		'form_name'=>'totalRoom',
		'title'=>'Total rooms',
		'mandatory'=>'Y',
		'input_type'=>'number',
		'input_value'=>'1',
		'column'=>'col-12 col-md-6 col-lg-3',
		'readonly'=>'',
		'disabled'=>'',
	),
	array(
		'form_name'=>'starRating',
		'title'=>'Star rating',
		'mandatory'=>'Y',
		'input_type'=>'select',
		'selection'=>array(
			array('data'=>'Select'),
			array('data'=>'★'),
			array('data'=>'★★'),
			array('data'=>'★★★'),
			array('data'=>'★★★★'),
			array('data'=>'★★★★★'),
			array('data'=>'★☆ (1.5)'),
			array('data'=>'★★☆ (2.5)'),
			array('data'=>'★★★☆ (3.5)'),
			array('data'=>'★★★★☆ (4.5)'),
		),
		'column'=>'col-12 col-md-6 col-lg-3',
		'readonly'=>'',
		'disabled'=>'',
	),
	array(
		'form_name'=>'hotel_hashtag',
		'title'=>'Sha Plus',
		'mandatory'=>'Y',
		'input_type'=>'select',
		'selection'=>array(
			array('data'=>'Not specify'),
			array('data'=>'SHA'),
			array('data'=>'SHA Plus'),
			array('data'=>'SHA Extra Plus'),
		),
		'column'=>'col-12 col-md-6 col-lg-3',
		'readonly'=>'',
		'disabled'=>'',
	),
	*/
);

?>
